# see https://github.com/crate-ci/typos

# a generic spell-checker that works on source code is quite
# tricky, so some false positives are fine

[files]
extend-exclude = ["LICENSE", "misc/*/packages.txt", "misc/*/*/packages.txt"]

[default.extend-identifiers]
# misc variable names & symbols
acc_spawnve = "acc_spawnve"
ba = "ba"
fo = "fo"
fof = "fof"
O_WRONLY = "O_WRONLY"
# clang-analyzer-optin.cplusplus
optin = "optin"
sidelen = "sidelen"
tpos = "tpos"
# assembly sources
CArry = "CArry"
hda = "hda"
Larg = "Larg"
pard = "pard"
suble = "suble"

# identifiers are intelligently split into words and then checked again
[default.extend-words]
delt = "delt"
FO = "FO"
fo = "fo"
# parm is used like param
PARM = "PARM"
parm = "parm"
# rela: ELF relocations
RELA = "RELA"
rela = "rela"
# siz is used for size
siz = "siz"
# SEH: Structured Exception Handling
SEH = "SEH"
seh = "seh"
