name: 'Static Analyzer - scan-build'

on:
  schedule:
    - cron: '40 1 * * 3'
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    container: 'alpine:edge'
    steps:
      - name: 'Install packages'
        run: 'apk update && apk upgrade && apk add bash clang clang-analyzer cmake g++ git make'
      - name: 'Check out code'
        uses: actions/checkout@v3
        with: { submodules: true }
      - name: 'Perform scan-build Analysis Debug'
        run: 'make build/extra/scan-build/debug'
      - name: 'Perform scan-build Analysis Release'
        run: 'make build/extra/scan-build/release'
